SELECT
    PAYMENT_KEY,
    COUSTOMER_KEY CUSTOMER_KEY,
    TIME_KEY,
    ITEM_KEY,
    STORE_KEY,
    CAST(QUANTITY AS DECIMAL(4,2)) QUANTITY,
    UNIT,
    CAST(UNIT_PRICE AS DECIMAL(10,2)) UNIT_PRICE,
    CAST(TOTAL_PRICE AS DECIMAL(10,2)) TOTAL_PRICE
FROM 
    {{ source("ecom","fact")}}
